# Generated by Django 2.0.7 on 2018-07-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
