# Generated by Django 2.0.7 on 2018-08-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0002_auto_20180731_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='album_logo',
            new_name='topic_logo',
        ),
    ]
