# Generated by Django 2.0.7 on 2018-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0004_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(blank=True),
        ),
    ]
