# Generated by Django 2.0.7 on 2018-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0005_auto_20180805_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
