# Generated by Django 2.0.7 on 2018-08-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0009_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='needs_improvement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
