# Generated by Django 2.0.7 on 2018-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0010_auto_20180822_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='needs_improvement',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
