# Generated by Django 2.0.7 on 2018-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0011_auto_20180825_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
