# Generated by Django 2.0.7 on 2018-09-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0014_auto_20180913_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
