# Generated by Django 2.0.7 on 2018-09-15 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeQta', '0015_remove_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='followers',
        ),
        migrations.AddField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
