# Generated by Django 2.0.7 on 2018-09-15 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0016_auto_20180915_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
