# Generated by Django 2.0.7 on 2018-09-16 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FeQta', '0017_auto_20180915_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='follow',
        ),
        migrations.AddField(
            model_name='question',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='question_followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='topic_followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
