# Generated by Django 2.0.7 on 2018-09-16 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0018_auto_20180916_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='follow',
            new_name='followers',
        ),
        migrations.AlterField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='topics_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
