# Generated by Django 2.0.7 on 2018-09-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0020_auto_20180916_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
