# Generated by Django 2.0.7 on 2018-10-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0021_answer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
