# Generated by Django 2.0.7 on 2018-10-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0022_profile_activation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
    ]
