# Generated by Django 2.0.7 on 2018-10-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0023_remove_profile_activation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activated',
        ),
    ]
