# Generated by Django 2.0.7 on 2018-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0024_remove_profile_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
