# Generated by Django 2.0.7 on 2018-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0025_auto_20181020_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
