# Generated by Django 2.0.7 on 2018-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0026_profile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
