# Generated by Django 2.0.7 on 2018-10-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeQta', '0027_auto_20181020_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
